# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

#
# YAML variable templates
#
job_defaults: &job_defaults
  working_directory: ~/pluginus-repo
  docker:
    - image: circleci/node:lts

#
# Run all jobs in sequence
#
workflows:
  version: 2
  deploy_npm:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
      - test:
          filters:
            branches:
              only:
                - master
          requires:
            - setup
      - coverage:
          filters:
            branches:
              only:
                - master
          requires:
            - test
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - coverage

#
# Define atomic jobs
#
jobs:
  setup:
    <<: *job_defaults

    steps:
      - checkout

      - run:
          name: "pluginus: Install npm packages"
          command: "npm run setup:ci"

      - run:
          name: "pluginus: Babel compile"
          command: "npm run build:ci"

      - save_cache:
          paths:
            - node_modules
            - dist
          key: pluginus-{{ .Branch }}-{{ checksum "package.json" }}

  test:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - pluginus-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: "pluginus: Run linter"
          command: "npm run lint"

      - run:
          name: "pluginus: Run tests"
          command: "npm test"

  coverage:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - pluginus-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: "pluginus: Publish test coverage to COVERALLS"
          command: "npm run coverage:ci"

  publish:
    <<: *job_defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - pluginus-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: "pluginus: Release to npm with semantic-release"
          command: "npx semantic-release"

